config/routes.rb
Rails.application.routes.draw do

  # prescriptool.com -> www.prescriptool.com
  match "(*any)",
  to: redirect( subdomain: "www"),
  via: :all,
  constraints: { subdomain: "", domain: "prescriptool.com"  }

  devise_for :users
  resources :prescriptions, only: %i[index show new create] do
    member do
      get :qr
      get :archive
    end
    collection do
      get :archived
    end
  end
  resources :notifications, only: %i[index]

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  DOSAGE = [
    "one pill every morning for one month",
    "two pills during lunch for two weeks",
    "one pill before sleeping during six months",
    "one pill two hours before eating for one week",
    "500mg, 2pills, every 6 hours",
    "20mg, 1pill, one hour before lunch"
  ]

  belongs_to :professional, class_name: "User"
  belongs_to :patient, class_name: "User"

  has_many :meds_prescriptions
  has_many :meds, through: :meds_prescriptions, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  scope :active, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }

  accepts_nested_attributes_for :meds_prescriptions

  def archive
    meds_prescriptions.each do |meds_prescription|
      meds_prescription.update(refill: [meds_prescription.refill - 1, 0].max)
    end

    update(archived: meds_prescriptions.map(&:refill).all?(&:zero?))
  end
end

app/controllers/prescriptions_controller.rb
require "rqrcode"

class PrescriptionsController < ApplicationController
  before_action :find_by_id, only: [:show, :archive, :qr]

  def index
    @prescriptions = policy_scope(Prescription)
    @prescriptions_pro = current_user.prescriptions_as_professional.active

    if params[:query].present?
      @query = params[:query]
      @results = PgSearch.multisearch(@query)
      if @results.empty?
        @prescriptions = current_user.prescriptions_as_patient.active
        flash[:alert] = "No results found. Please try again."
      end
      @results.each do |result|
        if result.searchable_type == "User"
          if current_user.pro?
            @prescriptions_pro = policy_scope(Prescription).where(patient: result.searchable, professional: current_user)
          else
            @prescriptions = policy_scope(Prescription).where(professional: result.searchable, patient: current_user)
          end
        elsif result.searchable_type == "Med"
          if current_user.pro?
            @prescriptions_pro = result.searchable.prescriptions.where(professional: current_user)
            # raise
          else
            @prescriptions = result.searchable.prescriptions.where(patient: current_user)
          end
        end
      end
    else
      @prescriptions = current_user.prescriptions_as_patient.active
      @prescriptions_pro = current_user.prescriptions_as_professional.active
    end
  end

  def show
    authorize @prescription
    createqr_code(create_string(@prescription))
    # qrcode = RQRCode::QRCode.new("#{request.base_url}/prescriptions/#{@prescription.id}")
  end

  def qr
    authorize @prescription
    createqr_code(create_string(@prescription))
    render plain: @svg_big.html_safe, content_type: 'image/svg+xml'
  end

  def archive
    authorize @prescription
    @prescription.archive
    redirect_to prescriptions_path
  end

  def archived
    @prescriptions = policy_scope(Prescription)
    # @prescriptions = current_user.prescriptions_as_patient.archived
    policy_scope(Prescription)
    current_user.pro ? @prescriptions = current_user.prescriptions_as_professional.archived : @prescriptions = current_user.prescriptions_as_patient.archived
  end

  def new
    @prescription = current_user.prescriptions_as_professional.new
    2.times.each do
      @prescription.meds_prescriptions.build
    end
    authorize @prescription
  end

  def create
    @prescription = current_user.prescriptions_as_professional.new(prescription_params)
    authorize @prescription

    if @prescription.save
      @notification = Notification.create(user: @prescription.patient, message: "You have a new prescription from Dr #{current_user.last_name}")
      redirect_to prescriptions_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def prescription_params
    params.require(:prescription).permit(
      :patient_id,
      :archived,
      meds_prescriptions_attributes: [
        :med_id,
        :dosage,
        :refill
      ]
    )
  end

  def find_by_id
    # @prescription = current_user.prescriptions_as_patient.find(params[:id])
    current_user.pro ? @prescription = current_user.prescriptions_as_professional.find(params[:id]) : @prescription = current_user.prescriptions_as_patient.find(params[:id])
  end

  def create_string(prescription)
    data_array = ""
    data_array += "#{prescription.created_at.strftime('%a %d %b %Y')}\n"
    data_array += "Dr #{prescription.professional.last_name}\n"
    data_array += "Patient: #{prescription.patient.first_name} #{prescription.patient.last_name}\n"
    prescription.meds.each do |med|
      data_array += "#{med.name}: "
      med.meds_prescriptions.each do |meds_prescription|
        data_array += "#{meds_prescription.dosage}\n" if prescription.id == meds_prescription.prescription_id
      end
    end
    data_array
  end

  def createqr_code(data_array)
    qrcode = RQRCode::QRCode.new(data_array)
    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 1,
      standalone: true,
      use_path: true
    )
    @svg_big = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 4,
      standalone: true,
      use_path: true
    )
  end
end

app/views/prescriptions/_prescriptions.html.erb
<div class="row justify-content-center">
  <div class="cards" data-controller="prescription-list">
    <% prescriptions.each do |prescription| %>
      <div class="card" data-action="click->prescription-list#toggleItem" data-prescription-list-target="card">
        <div class="header">
          <p class="name"><%= current_user.pro ? "#{prescription.patient.first_name} #{prescription.patient.last_name}": "Dr. #{prescription.professional.last_name}"%></p>
          <p class="date"><%= prescription.created_at.strftime('%a %d %b %Y') %></p>
        </div>
        <ul>
          <% prescription.meds_prescriptions.each do |med_prescription| %>
            <li>
              <i class="fa-solid fa-pills med-list-bullet"></i>
              <span class="med-name"><%= med_prescription.med.name %></span>
              <p class="details">
                <%= med_prescription.dosage %>
                (<%= pluralize(med_prescription.refill,'time')%>)
              <p>
            </li>
          <% end %>
        </ul>
        <div class="details">
          <p>Please deliver to: <%= prescription.patient.first_name %> <%=prescription.patient.last_name %> </p>
          <p>Dr. <%= prescription.professional.last_name%>, <%= prescription.professional.address %></p>
          <% if !prescription.archived? && current_user.pro %>
            <div>
              <%= link_to "ARCHIVE", archive_prescription_path(prescription), class: "btn btn-secondary",
              dataAction: "foo" %>
            </div>
          <% end %>
          <% if prescription.archived? %>
            <p id="important">This prescription has already been delivered: please do not deliver more!</p>
          <% end %>
        </div>
        <% if !prescription.archived? && !current_user.pro %>
          <a href="#"
            class="qrcode"
            data-action="click->prescription-list#swallow"
            data-bs-toggle="modal" data-bs-target="#showQrModal" data-id="<%= prescription.id %>"
          >
            <%= image_tag "qrcode.jpeg" %>
          </a>
        <% end %>

      </div>
    <% end %>

    <div class="modal fade" id="showQrModal" tabindex="-1" aria-hidden="true"
          data-action="show.bs.modal->prescription-list#onModalShow"
      >
      <div class="modal-dialog d-flex justify-content-center w-full mt-4">
        <div class="modal-content w-60 rounded-4">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body d-flex justify-content-center pb-5">
            <img data-prescription-list-target="modalqr">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prescriptions/_qrcode.html.erb
<%= svg.html_safe %>

app/views/prescriptions/archived.html.erb
<% content_for :meta_title, "Your archived prescriptions" %>

<div class="container prescriptions-container">
<h3>Archived prescriptions</h3>
<%= render "prescriptions/prescriptions", prescriptions: @prescriptions %>
</div>

app/views/prescriptions/index.html.erb
<% content_for :meta_title, "Your prescriptions" %>

<div class="container prescriptions-container">
<h3>Your prescriptions</h3>
<%= render "prescriptions/prescriptions", prescriptions: current_user.pro ? @prescriptions_pro : @prescriptions %>
</div>

app/views/prescriptions/new.html.erb
<% content_for :meta_title, "Create a prescription" %>
<h3 id="H1"> Doctor, please complete the form below </h3>
<div class="container-prescription">
  <%= simple_form_for @prescription do |f| %>
    <%= f.association :patient, collection: User.patients, label_method: :full_name %>
    <%= f.simple_fields_for :meds_prescriptions do |a| %>
      <%= a.association :med, collection: Med.all %>
      <%= a.input :dosage, collection: Prescription::DOSAGE %>
      <%= a.input :refill, collection: (0..3) %>
    <% end %>
    <div class="container-button">
      <%= f.button :submit, class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/prescriptions/show.html.erb
<div class="container-prescription-show">
  <%# <div class="container-relative"> %>
  <div class="d-flex justify-content-between">
    <h3>Prescription <%= @prescription.id %></h3>
    <div class="qrcode-show">
      <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <%= @svg.html_safe %>
      </a>
    </div>
  </div>
  <p class="container-doctor">Doctor <%= @prescription.professional.last_name%></p>
  <p class="container-doctor"><%= @prescription.professional.address%></p>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog d-flex justify-content-center w-full mt-4">
      <div class="modal-content w-60 rounded-4">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center p-3">
          <%= @svg_big.html_safe %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <p class="container-date"><%= @prescription.created_at.strftime('%a %d %b %Y') %></p>
    <div class="content">
      <p><u>Please deliver to <%= @prescription.patient.first_name%> <%=@prescription.patient.last_name %> </u></p>
      <% @prescription.meds_prescriptions.each do |med_prescription| %>
        <%= med_prescription.med.name %>
        <%= med_prescription.dosage %>
      <% end %>
    </div>
  </div>
  <% unless @prescription.archived? %>
    <div class="container-button-archived">
      <%# <%= simple_form_for(@prescription, url: archive_prescription_path(@prescription)) do |f| %>
        <%# <%= f.input :archived, :label => "SCAN QRCODE", as: :boolean, input_html: { class: "toggle", onchange: 'this.form.submit()' }  %>
        <%# <% end %>
      </div>
    <% end %>
    <div class="seal">
      <p id="p2"><em>Prescription generated by Prescriptool</em></p>
    </div>
    <%# </div> %>
  </div>