config/routes.rb
Rails.application.routes.draw do

  # prescriptool.com -> www.prescriptool.com
  match "(*any)",
  to: redirect( subdomain: "www"),
  via: :all,
  constraints: { subdomain: "", domain: "prescriptool.com"  }

  devise_for :users
  resources :prescriptions, only: %i[index show new create] do
    member do
      get :qr
      get :archive
    end
    collection do
      get :archived
    end
  end
  resources :notifications, only: %i[index]

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/33clouds/prescriptool"><i class="fa-brands fa-github-alt"></i></a>
    <a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <p>This site was coded with <i class="fa-solid fa-heart fa-beat"></i></p>
  </div>
  <div class="footer-address">
    <p><strong>Prescriptool</strong>, <nobr>54 quai Charles Pasqua,</nobr> <nobr>92300 Levallois-Perret</nobr></p>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="search">
  <div class="container-fluid d-flex justify-content-between" data-search-target="navbar">
    <%= link_to "/", class: "navbar-brand" do %>
      <div class="d-flex align-items-center">
        <div class="brand-icon">
          <i class="fa-regular fa-file-powerpoint"></i>
        </div>
        <div>
          <h5 class="prescriptool-brand">Prescriptool</h5>
          <p class="grey-text brand-subtitle">Generates unique prescriptions</p>
        </div>
      </div>
    <% end %>
    <% if user_signed_in? %>
    <div data-action="click->search#expand"><a class="my-2 my-sm-0"><i class="fa-solid fa-magnifying-glass"></i></a>
    </div>
    <% end %>
    <div id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "user_pic.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# greeting %>
              <span class="dropdown-item">Hello,
                <% if current_user.pro? %>
                  <strong>Dr. <%= current_user.last_name %> 💊</strong>
                <% else %>
                  <strong><%= current_user.first_name %> 👑</strong>
                <% end %>
              </span>
              <div class="dropdown-divider"></div>
              <%= link_to "Archived prescriptions", archived_prescriptions_path , class: "dropdown-item" %>
              <% if @current_user.pro? %>
                <%= link_to "Create a new prescription", new_prescription_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Notifications", notifications_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <%# We display this if the user clicks on the search icon %>
  <form class="form-inline d-flex" action="<%= prescriptions_path %>">
    <div class="container-fluid d-flex justify-content-between d-none" data-search-target="searchnavbar">
      <a class="my-2 my-sm-0" data-action="click->search#expand">
        <i class="fa-solid fa-arrow-left"></i>
      </a>
      <div class="search">
        <input class="form-control mr-sm-2" type="search" placeholder="Doctor or medication" aria-label="Search" name="query">
      </div>
    </div>
  </form>
</div>